controllers:
    resource:
        path: ../src/Application/
        namespace: App\Controller
    type: attribute

# User
#sign-in:
#    path: /user/sign-in
#    controller: App\Application\Controller\User\SignInController
#
#save-owner:
#    path: /user/save-owner
#    controller: App\Application\Controller\User\SaveOwnerController
#
#delete-owner:
#    path: /user/delete-owner
#    controller: App\Application\Controller\User\DeleteOwnerController
#
#find-owner:
#    path: /user/find-owner
#    controller: App\Application\Controller\User\FindOwnerController
#
#save-tenant:
#    path: /user/save-tenant
#    controller: App\Application\Controller\User\SaveTenantController
#
#save-guarantor:
#    path: /user/save-guarantor
#    controller: App\Application\Controller\User\SaveGuarantorController
#
#save-subscriber:
#    path: /user/save-subscriber
#    controller: App\Application\Controller\User\SubscriberSaveController
#
#delete-subscriber:
#    path: /user/delete-subscriber
#    controller: App\Application\Controller\User\SubscriberDeleteController

# Country
get-countries:
    path: /country/get
    controller: App\Application\Controller\Country\GetCountryController

# Civility
get-civilities:
    path: /civility/get
    controller: App\Application\Controller\Civility\GetCivilityController

# Marital Status
get-marital-status:
    path: /marital-status/get
    controller: App\Application\Controller\MaritalStatus\GetMaritalStatusController

# City
#get-cities:
#    path: /city/list
#    controller: App\Application\Controller\City\ListController
#
#get-cities-by-zip-code:
#    path: /city/list-by-zip-code
#    controller: App\Application\Controller\City\ListByZipCodeController
#
## Corporation
#save-corporation:
#    path: /corporation/save
#    controller: App\Application\Controller\Corporation\SaveController
#
#delete-corporation:
#    path: /corporation/delete
#    controller: App\Application\Controller\Corporation\DeleteController
#
## Situation
#professional-situation:
#    path: /situation/list
#    controller: App\Application\Controller\Situation\ProfessionalSituationController
#
## Possession
#save-possession:
#    path: /possession/save
#    controller: App\Application\Controller\Possession\SaveController
#
## Service
#save-service:
#    path: /service/save
#    controller: App\Application\Controller\Service\SaveController
#
## Mandate
#find-mandate:
#    path: /mandate/find
#    controller: App\Application\Controller\Mandate\FindController